openapi: 3.0.1
info:
  title: Notificaciones a usuarios
  description: API de notificaciones del proyecto Dámaso. Ingeniería de Servicios TIC, Universidad de Extremadura
  contact:
    email: jgarciasex@alumnos.unex.es
  version: 1.0.0
servers:
- url: https://localhost:8080/notificationapi
tags:
  - name: Notificación
    description: Notificaciones al usuario
paths:
  /notifications:
    post:
      tags:
        - Notificación
      summary: Crea una nueva notificación para el usuario.
      operationId: addNotification
      requestBody:
        description: Contenido de la notificación que se le envía al usuario.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
        required: true
      responses:
        '200':
          description: Correcto
          content: 
            application/json:
              schema:
                  type: object
                  properties:
                    notificationID:
                      type: integer
                      format: int64
                      description: ID asignado a la notificación
        '405':
          description: Entrada inválida
          content: {}
    get:
      tags:
        - Notificación
      summary: Obtiene todas las notificaciones.
      description: Obtiene todas las notificaciones que todavía están en espera.
      operationId: getNotifications
      responses:
        '200':
          description: Correcto
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '408':
          description: Lista vacía
          content: {}
  '/notifications/{notificationID}':
    get:
      tags:
        - Notificación
      summary: Obtiene la información de una notificación en concreto.
      description: Obtiene la información de una notificación en concreto, ya esté en espera o confirmada.
      operationId: getNotification
      parameters:
        - name: notificationID
          in: path
          description: ID de la notificación a comprobar
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Correcto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '404':
          description: Notificación no encontrada
          content: {}
        '405':
          description: Formato de entrada inválido
          content: {}
    delete:
      tags:
        - Notificación
      summary: Cancela una notificación.
      description: Cancela una notificación si aún no ha sido confirmada.
      operationId: deleteNotification
      parameters:
        - name: notificationID
          in: path
          description: ID de la notificación a cancelar
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Correcto
          content: {}
        '404':
          description: Notificación no encontrada
          content: {}
        '405':
          description: Formato de entrada inválido
          content: {}
        '407':
          description: Notificación ya confirmada
          content: {}
    put:
      tags:
        - Notificación
      summary: Confirma que se ha recibido una notificación y envía el resultado
      operationId: confirmNotification
      parameters:
        - name: notificationID
          in: path
          description: ID de la notificación a confirmar
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Valor de la confirmación
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification/properties/valueConfirmation'
      responses:
        '200':
          description: Correcto
          content: {}
        '404':
          description: Notificación no encontrada
          content: {}
        '405':
          description: Formato de entrada inválido
          content: {}
components:
  schemas:
    Notification:
      type: object
      properties:
        notificationID:
          description: Identificador de la notificación.
          type: integer
          format: int64
          example: 12345
        content:
          type: string
          description: Contiene el mensaje de la notificación.
          example: "¡Hora de tomar el ibuprofeno!"
        confirmed:
          description: Estado de la confirmación. True confirmado y False no confirmado.
          type: boolean
          default: false
          example: false
        valueConfirmation:
          description: Valor de la confirmación y momento de la confirmación
          type: object
          properties:
            value:
              description: Valor de la confirmación
              type: boolean
              example: false
            timestamp:
              description: Momento de la confirmación
              type: string
              format: date-time
        notificationType:
          description: Identifica el tipo de notificación que se va a enviar
          type: string
          example: medicine
          enum:
            - medicine
            - food
            - inactivity
