openapi: 3.0.1
info:
  title: Dámaso Recordatorios API
  description: API de recordatorios del proyecto Dámaso. Ingeniería de Servicios TIC,
    Universidad de Extremadura
  contact:
    email: speaborr@alumnos.unex.es
  version: 1.0.0
servers:
- url: https://localhost:8080/remindersapi
tags:
- name: Recordatorios
  description: Operaciones relacionadas con los recordatorios
- name: Configuración
  description: Cambios de configuración de recordatorios
paths:
  /reminders:
    get:
      tags:
      - Recordatorios
      summary: Obtiene todos los recordatorios
      description: Devuelve la lista de recordatorios
      operationId: getReminders
      responses:
        200:
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reminder'
        405:
          description: Entrada inválida
          content: {}
        408:
          description: No se encontraron recordatorios
          content: {}
    post:
      tags:
      - Recordatorios
      summary: Añade un nuevo recordatorio
      operationId: addReminder
      requestBody:
        description: Añade un nuevo recordatorio
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reminder'
        required: true
      responses:
        200:
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: ID del recordatorio
        405:
          description: Entrada inválida
          content: {}
  /reminders/{reminderId}:
    get:
      tags:
      - Recordatorios
      summary: Busca un recordatorio por ID
      description: Devuelve el recordatorio cuyo ID sea el indicado
      operationId: getReminderById
      parameters:
      - name: reminderId
        in: path
        description: ID del recordatorio
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reminder'
        405:
          description: Entrada inválida
          content: {}
        404:
          description: No se encontró el recordatorio
          content: {}
    put:
      tags:
      - Recordatorios
      summary: Actualiza un recordatorio existente
      description: Modifica la información de un recordatorio existente
      operationId: updateReminder
      parameters:
      - name: reminderId
        in: path
        description: ID del recordatorio a modificar
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Información con la que se va a actualizar el recordatorio
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reminder'
        required: true
      responses:
        405:
          description: Entrada inválida
          content: {}
        404:
          description: No se encontró el recordatorio
          content: {}
    delete:
      tags:
      - Recordatorios
      summary: Cancelar un recordatorio
      description: Cancela un recordatorio de la lista de recordatorios
      operationId: cancelReminder
      parameters:
      - name: reminderId
        in: path
        description: ID del recordatorio a cancelar
        required: true
        schema:
          type: integer
          format: int64
      responses:
        405:
          description: Entrada inválida
          content: {}
        404:
          description: No se encontró el recordatorio
          content: {}
  /reminders/reminderstype/{reminderType}:
    get:
      tags:
      - Recordatorios
      summary: Busca los recordatorios por tipo
      description: Devuelve los recordatorios cuyo tipo sea el indicado
      operationId: getReminderByType
      parameters:
      - name: reminderType
        in: path
        description: tipo del recordatorio
        required: true
        schema:
          type: string
          enum:
          - medicine
          - food
          - inactivity
      responses:
        200:
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reminder'
        405:
          description: Entrada inválida
          content: {}
        408:
          description: No se encontraron recordatorios
          content: {}
  /configuration:
    get:
      tags:
      - Configuración
      summary: Obtener configuración
      description: Cargar la configuración del sistema
      operationId: getConf
      responses:
        200:
          description: Operación realizada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
    put:
      tags: 
      - Configuración
      summary: Cambiar configuración
      description: Permite cambiar la configuración del sistema
      operationId: updateConf
      requestBody:
        description: Nueva configuración
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Configuration'
      responses:
        200:
          description: Operación realizada con éxito
          content: {}
        405:
          description: Entrada inválida
          content: {}
components:
  schemas:
    Reminder:
      required:
      - id
      - type
      - date
      type: object
      properties:
        id:
          type: integer
          description: ID del recordatorio
          format: int64
          example: 124132
        type:
          type: string
          description: Tipo de recordatorio
          enum:
          - medicine
          - food
          - inactivity
          example: food
        date:
          type: string
          description: Fecha en la que se realizará el recordatorio
          format: date-time
        complete:
          type: boolean
          description: Indica si el recordatorio está completo o no
          default: false
          example: false
    Configuration:
      required: 
      - maxReminders
      type: object
      properties:
        maxReminders:
          type: integer
          format: int32
          description: Número máximo de recordatorios a realizar
          default: 4
          example: 3
